---
title: "Código gráficos"
author: "Albert Gutiérrez"
date: "2023-10-25"
output: html_document
---



```{r cars}
library(tidyverse)
library(ggplot2)


ruta_excel2 <- "C:/Users/alber/OneDrive/Escritorio/II Semestre 2023/Estadística/Proyecto Estadística/Datos/Tablas/Indicadores.xlsx"

# Lee el archivo de Excel
df <- read_excel(ruta_excel2)

#Se calcula el promedio de los indicadores y se convierten en una nueva tabla.
mean_df <- colMeans(df, na.rm = TRUE) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Columna") %>% 
  rename(Promedio = ".")

```

## Gráfico 1

```{r pressure, echo=FALSE}
library(ggplot2)
library(stringr) #Se usa para usar la funcion "str_warp" que ajusta el texto en el eje y.

grafico1 <- ggplot(mean_df, aes(x = reorder(Columna, Promedio), y = Promedio)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = round(Promedio, 1)), hjust = 0.1) +
  coord_flip() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.text.y = element_text(angle = 0, hjust = 1, size = 10)) + # Ajuste del tamaño del texto
  labs(x = "Deprivaciones", y = "Porcentaje", title = "") +
  scale_y_continuous(labels = function(x) str_wrap(x, width = 11), breaks = seq(ceiling(min(mean_df$Promedio)), ceiling(max(mean_df$Promedio)), by = 4))

print(grafico1)
# Guarda los gráficos combinados como una imagen.
ggsave("mis_grafico1.png", grafico1, bg="white")
```

##Gráfico 2
```{r}
ruta_excel4 <- "C:/Users/alber/OneDrive/Escritorio/II Semestre 2023/Estadística/Proyecto Estadística/Datos/Tabla Limpia.xlsx"
tabla_limpia <- read_excel(ruta_excel4)
library(ggplot2)
library(stringr)


# Se crea un vector con las traducciones
traducciones <- c("Europe and Central Asia" = "Europa y Asia Central",
                  "Arab States" = "Estados Árabes",
                  "Latin America and the Caribbean" = "América Latina y el Caribe",
                  "East Asia and the Pacific" = "Asia Oriental y el Pacífico",
                  "South Asia" = "Asia del Sur",
                  "Sub-Saharan Africa" = "África Subsahariana"
)

# Reemplaza los nombres de las regiones en inglés por los nombres en español en la tabla
tabla_limpia$Región <- traducciones[tabla_limpia$Región]

# Creación del gráfico de cajas
cajas <- ggplot(tabla_limpia, aes(x = `Región`, y = `IPM (0 a 1)`)) +
  geom_boxplot(fill = "steelblue") + 
  labs(title = "",
       x = "Región",
       y = "IPM") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05)) + # Ajusta las etiquetas del eje y
  theme_bw() + #Cambia el fondo a blanco
  theme(plot.background = element_rect(fill = "white")) 

print(cajas)
# Guarda los gráficos combinados como una imagen.
ggsave("mi_grafica4.png", cajas, bg="white")


```


##Gráfico 3 

```{r}
library(gridExtra) #Esta librería se usará para poder unir varios gráficos en uno
ruta_excel3 <- "C:/Users/alber/OneDrive/Escritorio/II Semestre 2023/Estadística/Proyecto Estadística/Datos/Tablas/3 Dimensiones.xlsx"


df <- read_excel(ruta_excel3)
p1 <- ggplot(df, aes(x=Salud, y=Educación)) +
  geom_point(color = "steelblue") +
  labs(x="Salud", y="Educación", 
       title="") +
  theme_minimal()

p2 <- ggplot(df, aes(x=Salud, y=`Estándares de Vida`)) +
  geom_point(color = "steelblue") +
  labs(x="Salud", y="Estándares de Vida", 
       title="") +
  theme_minimal()

p3 <- ggplot(df, aes(x=Educación, y=`Estándares de Vida`)) +
  geom_point(color = "steelblue") +
  labs(x="Educación", y="Estándares de Vida", 
       title="") +
  theme_minimal()

# Se combinan los gráficos:
grafico3<-grid.arrange(p1, p2, p3, nrow = 1)


# Guarda los gráficos combinados como una imagen.
ggsave("mis_grafico3.png", grafico3)

```

